FROM uglyduckling.nl/serf-base
MAINTAINER amouat "a.mouat@uglyduckling.nl"

# Have some more python requirements
RUN apt-get install -y python2.7-dev curl
RUN pip install flask twisted autobahn requests


ADD /serf/serf /usr/local/bin/serf
ADD /serf/supervisor_conf /etc/supervisor/conf.d
ADD /serf/scripts /

ADD /ui/app /app
ADD /ui/UIEventHandler.py /
#RUN pip install -r /tmp/requirements.txt

# Run wrapper for serf (is this already getting run?
ADD ui/scripts/ /
EXPOSE 5000
CMD bash /init.sh
