FROM ubuntu
MAINTAINER Pini Reznik "p.reznik@uglyduckling.nl"

RUN echo deb http://archive.ubuntu.com/ubuntu precise universe >> /etc/apt/sources.list
RUN apt-get update

RUN apt-get install -y unzip lsb-release wget ca-certificates supervisor python-pip libyaml-0-2 gcc

# Add the requirements.txt and ask pip to install everything
ADD serf/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

