FROM uglyduckling.nl/serf-base
MAINTAINER Pini Reznik "p.reznik@uglyduckling.nl"


ADD /skynet/serf /usr/local/bin/serf

ADD /database/supervisor_conf /etc/supervisor/conf.d
ADD /database/scripts /

# Run wrapper for serf
CMD bash /serf.sh

